#!/bin/bash
if [ ! -d /etc/paw ] ; then
	mkdir /etc/paw
fi

if [ ! -d /usr/lib/paw ] ; then
    mkdir /usr/lib/paw
fi
if [ ! -d /usr/lib/paw/lib ] ; then
    mkdir /usr/lib/paw/lib
fi

cp -f -r * /usr/lib/paw/

ln -f -s /usr/lib/paw/lib/paw.conf /etc/paw/paw.conf
ln -f -s /usr/lib/paw/lib/paw /etc/init.d/paw
ln -f -s /usr/lib/paw/lib/server /usr/sbin/paw
